Created Custom Turtle post without the assignment in there yet
inf380p/fall2021 pull request #37
Opened 2020-09-03 05:57 UTC by EAkita

2020-09-07 16:55 UTC, eah13 requested changes
You're missing a `"` but everything else is technically correct.

Some of your messages to humans are misleading, though. When you edited the text to embed the trinket it would've been nice to change the post text to something like "Here's my custom turtle:".

And the pull request title says the assignment isn't in there yet but it is! Be nice to your humans and try to keep the title and description of your pull requests updated alongside the code.

Since you'll already be editing the post, consider addressing these as well.

2020-09-07 16:55 UTC, eah13 commented on _posts/eakita/2020-09-02-eakita-custom-turtle.md
> +title: "EAkita's Custom Turtle
Missing the second `"` here.

2020-09-16 18:08 UTC, EAkita commented on _posts/eakita/2020-09-02-eakita-custom-turtle.md
> +title: "EAkita's Custom Turtle
@eah13 Thanks! just made the change

2020-09-16 18:09 UTC, EAkita commented
@eah13 made the change. Kindly review when you get a chance

2020-09-23 15:13 UTC, eah13 approved these changes
Code looks good! Your messages to humans on this pull request (title, description) could've been a little more descriptive though.

2020-09-23 15:13 UTC, merged