Andrew R's Project Update and Report (11/30)
inf380p/fall2021 pull request #586
Opened 2021-11-30 14:58 UTC by areiter18

2021-11-30 15:00 UTC, areiter18 reviewed
tweaked formatting

2021-11-30 15:03 UTC, areiter18 reviewed
tweaked formatting again

2021-12-01 04:20 UTC, MishaCienfuegos requested changes
Because I helped another student troubleshoot this recently, I know that the in order for your posts to show up in your People page, the file title needs to begin `YYYY-MM-DD-`. Yours has an underscore `_`, not a hyphen (`-`) at the end, which will cause issues. Would you mind switching that?

2021-12-01 04:21 UTC, MishaCienfuegos commented on _posts/areiter18/2021-11-30_ProjectUpdate_StandUpReport.md
> +<p>Essentially, I forgot to include the phrase ```break``` at the end, causing the code to continually loop and ask the same thing repeatedly if you selected a particular input. This was an important
Ooh, interesting choice to use html tags here!

2021-12-01 15:40 UTC, areiter18 reviewed
tweaked file name

2021-12-01 17:24 UTC, MishaCienfuegos approved these changes
Thanks for editing that! Merging now.

2021-12-01 17:25 UTC, merged