Includes my program for the Turtle exercise
inf380p/fall2021 pull request #61
Opened 2020-09-13 15:18 UTC by samandalib

2020-09-13 16:52 UTC, samandalib commented
Since I was behind the class schedule, I tried to make my turtle exercise as one that can cover all the topics discussed in three weeks that I missed. It covers : Custom Turtle, Logical Turtles Exercises, Turtlehacks, and Functional Turtles Exercise (It makes me a week ahead!).

2020-09-16 15:43 UTC, eah13 requested changes
Check the filename of your program. There's a very specific format you'll need to follow.

2020-09-16 15:43 UTC, eah13 commented on turtleProgram
> +author: Hesam
This needs to be your github username

2020-09-16 18:34 UTC, samandalib commented on turtleProgram
> +author: Hesam
Sorry about that! fixed it

2020-09-23 15:33 UTC, eah13 approved these changes
Nicely done.

2020-09-23 15:34 UTC, merged